import { useEffect, useRef, useState } from 'react';
import { onlineApi, type ConnectionState } from '../session/network';
import type { RoomCommandInput, RoomSummary, RoomView, SeatAccess } from '../session/protocol';

export function RecoveryCard({ access, onClose }: { access: SeatAccess; onClose: () => void }) {
  const [message, setMessage] = useState('');
  const text = `魔法运动员\n房间：${access.code}\n个人恢复码：${access.recoveryCode}\n请勿转发此码。使用后会自动换发新码。`;
  const download = () => { const url = URL.createObjectURL(new Blob([text], { type: 'text/plain;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = `魔法运动员-${access.code}-个人恢复码.txt`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); setMessage('已下载，请妥善保存'); };
  return <div className="drawer-overlay"><section className="recovery-card" role="dialog" aria-modal="true" aria-label="保存个人恢复码"><span className="eyebrow">YOUR SEAT, YOUR CODE</span><h2>保存你的个人恢复码</h2><p>原浏览器会自动记住座位。换电脑或清理浏览器后，可用此码恢复；它只属于你，请勿转发给其他玩家。</p><label>房间码<strong>{access.code}</strong></label><label>个人恢复码<code data-testid="recovery-code">{access.recoveryCode}</code></label><div className="online-buttons"><button className="secondary" onClick={() => void navigator.clipboard.writeText(text).then(() => setMessage('已复制')).catch(() => setMessage('复制失败，请下载或手动保存'))}>复制</button><button className="secondary" onClick={download}>下载恢复码</button></div><p role="status">{message || '恢复后会换发新码，旧设备将失去操作权限。'}</p><button className="primary" onClick={onClose}>我已保存，进入房间 →</button></section></div>;
}

export function OnlineHome({ onEnter, initialCode, onError }: { onEnter: (code: string, access?: SeatAccess) => void; initialCode: string; onError: (error: string) => void }) {
  const [tab, setTab] = useState<'create' | 'join' | 'recover'>(initialCode ? 'join' : 'create');
  const [name, setName] = useState(''); const [code, setCode] = useState(initialCode);
  const [recovery, setRecovery] = useState(''); const [capacity, setCapacity] = useState(4); const [duo, setDuo] = useState(false);
  const [rooms, setRooms] = useState<RoomSummary[]>([]); const [busy, setBusy] = useState(false);
  const [status, setStatus] = useState('正在连接联机服务…');
  const requestNumber = useRef(0);
  const refresh = () => { const request = ++requestNumber.current; setStatus('正在连接联机服务…'); onlineApi.session().then(data => { if(request !== requestNumber.current) return; setRooms(data.rooms); setStatus('联机服务已就绪'); if(initialCode && data.rooms.some(room => room.code === initialCode && room.status !== 'closed')) onEnter(initialCode); }).catch(e => { if(request === requestNumber.current) setStatus(e instanceof Error ? e.message : '联机服务暂不可用'); }); };
  useEffect(() => { refresh(); return () => { requestNumber.current++; }; }, []);
  const submit = async () => { setBusy(true); onError(''); try { const roomCode = code.trim().toUpperCase(); const access = tab === 'create' ? await onlineApi.create(name.trim() || '魔法选手', capacity, capacity === 2 || (capacity === 3 && duo)) : tab === 'join' ? await onlineApi.join(roomCode, name.trim() || '魔法选手') : await onlineApi.recover(roomCode, recovery.trim()); setRecovery(''); onEnter(access.code, access); } catch(e) { onError(e instanceof Error ? e.message : String(e)); } finally { setBusy(false); } };
  return <section className="setup-card online-home" data-testid="online-home"><div className="setup-heading"><span className="eyebrow">PLAY TOGETHER, ANYWHERE</span><h2>好友联机</h2><p>各自打开网页，在同一片魔法赛场相遇。</p></div><div className="online-tabs">{(['create','join','recover'] as const).map((value, i) => <button key={value} className={tab === value ? 'active' : ''} onClick={() => setTab(value)}>{['创建房间','加入房间','找回座位'][i]}</button>)}</div><form onSubmit={e => { e.preventDefault(); void submit(); }}>{tab !== 'recover' && <label className="online-field">你的昵称<input aria-label="联机昵称" maxLength={16} value={name} onChange={e => setName(e.target.value)} placeholder="魔法选手" autoComplete="nickname"/></label>}{tab !== 'create' && <label className="online-field">房间码<input aria-label="房间码" value={code} onChange={e => setCode(e.target.value.toUpperCase())} maxLength={12} required autoCapitalize="characters" autoComplete="off"/></label>}{tab === 'recover' && <label className="online-field">个人恢复码<input aria-label="个人恢复码" type="password" value={recovery} onChange={e => setRecovery(e.target.value)} required autoComplete="off"/></label>}{tab === 'create' && <><label className="field-label">参加人数</label><div className="player-count">{[2,3,4,5,6].map(n => <button type="button" key={n} className={capacity === n ? 'active' : ''} onClick={() => setCapacity(n)}>{n}<small>人</small></button>)}</div>{capacity === 3 && <label className="duo-option"><input type="checkbox" checked={duo} onChange={e => setDuo(e.target.checked)}/><span>双角色变体</span></label>}{capacity === 2 && <p className="mode-note">两人模式每位玩家每场派出两名运动员。</p>}</>}<button className="primary start-button" type="submit" disabled={busy} data-testid={`online-${tab}`}>{busy ? '正在处理…' : tab === 'create' ? '创建好友房 →' : tab === 'join' ? '加入好友房 →' : '恢复我的座位 →'}</button></form><div className="online-service"><span>{status}</span><button onClick={refresh}>刷新</button></div>{rooms.length > 0 && <div className="my-rooms"><h3>我的房间</h3>{rooms.map(room => <button key={room.code} onClick={() => onEnter(room.code)} data-testid={`resume-room-${room.code}`}><strong>{room.code}</strong><span>{room.name} · {room.status === 'lobby' ? '等待开赛' : room.status === 'playing' ? '比赛中' : room.status === 'finished' ? '已完赛' : '已结束'} →</span></button>)}</div>}<p className="mode-note">房间从最后一次有效活动起保留 7 天。掉线时会等待需要你决定的操作。</p></section>;
}

export function RoomBar({ room, connection, pending, command, onRecovery, onExit }: { room: RoomView; connection: ConnectionState; pending: boolean; command: (action: RoomCommandInput) => void; onRecovery: () => void; onExit: () => void }) {
  const [copied, setCopied] = useState(false); const host = room.hostSeatId === room.viewerSeatId;
  const online = connection === 'connected';
  const copyInvite = () => { const link = new URL(window.location.href); link.search = ''; link.hash = ''; link.searchParams.set('room', room.code); void navigator.clipboard.writeText(link.toString()).then(() => setCopied(true)).catch(() => { window.prompt('复制此邀请链接发送给朋友：', link.toString()); }); };
  return <section className="room-bar" data-testid="room-bar"><div><span className="eyebrow">FRIENDS ROOM</span><strong>房间 {room.code}</strong><span className={`connection-state ${connection}`}>{connection === 'connected' ? pending ? '正在确认操作…' : '已连接 · 服务端自动保存' : connection === 'revoked' ? '操作权已转移' : connection === 'connecting' ? '正在连接…' : '连接中断 · 自动重连中'}</span></div><div className="room-people">{room.seats.map(seat => <span key={seat.id} className={seat.online ? 'online' : 'offline'} title={seat.online ? '在线' : '离线，轮到时等待'}>{seat.online ? '●' : '○'} {seat.name}{seat.id === room.viewerSeatId && '（你）'}{seat.id === room.hostSeatId && ' ♛'}</span>)}</div><div className="room-actions"><button onClick={copyInvite}>{copied ? '邀请链接已复制' : '复制邀请链接'}</button><button disabled={!online || pending} onClick={onRecovery}>重新生成恢复码</button>{host && room.status !== 'closed' && <button disabled={!online || pending} onClick={() => { if(window.confirm('结束房间后无法继续本届比赛，确定结束？')) command({ type: 'close' }); }}>结束房间</button>}<button onClick={onExit}>返回首页</button></div><small>到期时间：{new Date(room.expiresAt).toLocaleString('zh-CN')}（有效操作后续期 7 天）</small></section>;
}

export function RoomLobby({ room, disabled, command }: { room: RoomView; disabled: boolean; command: (action: RoomCommandInput) => void }) {
  const me = room.seats.find(s => s.id === room.viewerSeatId); const host = room.hostSeatId === room.viewerSeatId;
  const [capacity, setCapacity] = useState(room.capacity); const [duo, setDuo] = useState(room.duo);
  useEffect(() => { setCapacity(room.capacity); setDuo(room.duo); }, [room.capacity, room.duo]);
  return <section className="room-lobby" data-testid="room-lobby"><div className="center-intro"><span className="eyebrow">THE MAGIC STARTS WITH FRIENDS</span><h1>{room.status === 'closed' ? '房间已结束' : '等待朋友们入场'}</h1><p>{room.status === 'closed' ? '返回首页创建新房间，再来一场。' : `${room.seats.length} / ${room.capacity} 人 · ${room.duo ? '双角色' : '常规'}模式 · 全员在线并准备后开赛`}</p></div><div className="lobby-seats">{room.seats.map((seat,i) => <div className="lobby-seat" key={seat.id}><span className={`name-dot color-${i}`}>{i+1}</span><strong>{seat.name}{seat.id === room.viewerSeatId && '（你）'}</strong><small>{seat.id === room.hostSeatId ? '房主 · ' : ''}{seat.online ? '在线' : '离线'} · {seat.ready ? '已准备 ✓' : '未准备'}</small>{host && seat.id !== me?.id && room.status === 'lobby' && <button disabled={disabled} onClick={() => { if(window.confirm(`将 ${seat.name} 移出房间？`)) command({ type: 'kick', seatId: seat.id }); }}>移出</button>}</div>)}{Array.from({length: Math.max(0, room.capacity-room.seats.length)}, (_,i) => <div className="lobby-seat empty" key={`empty-${i}`}>✦<strong>虚位以待</strong></div>)}</div>{room.status === 'lobby' && <><div className="online-buttons"><button className="primary" data-testid="room-ready" disabled={disabled} onClick={() => command({ type:'ready', ready: !me?.ready })}>{me?.ready ? '取消准备' : '我准备好了 →'}</button>{host && <button className="primary" data-testid="room-start" disabled={disabled || room.seats.length !== room.capacity || room.seats.some(s => !s.ready || !s.online)} onClick={() => command({ type:'start' })}>全员开赛 →</button>}<button className="secondary" disabled={disabled} onClick={() => { if(window.confirm('离开后此座位将被释放，确定离开？')) command({type:'leave'}); }}>离开房间</button></div>{host && <div className="room-config"><label>参加人数<select value={capacity} onChange={e => setCapacity(Number(e.target.value))} aria-label="房间参加人数">{[2,3,4,5,6].map(n => <option value={n} key={n}>{n} 人</option>)}</select></label>{capacity === 3 && <label><input type="checkbox" checked={duo} onChange={e => setDuo(e.target.checked)}/>双角色变体</label>}<button disabled={disabled || (capacity === room.capacity && (capacity === 2 || capacity === 3 && duo) === room.duo)} onClick={() => { if(window.confirm('修改设置会清除所有准备状态，确定修改？')) command({ type:'configure', capacity, duo: capacity === 2 || (capacity === 3 && duo) }); }}>更新房间设置</button></div>}</>}<p className="mode-note">离线玩家不会自动代打。房主离线 30 秒后自动转交房主身份。</p></section>;
}
